### ISSUE TITLE
code of Using Wasserstein Generative Adversial Networks for the Design of Monte Carlo Simulations 

### ISSUE THREAD

**Issue by 1013hdh** [evanmunro/evanmunro.github.io#1]
code of this paper "Using Wasserstein Generative Adversarial Networks for the Design of Monte Carlo Simulations" in  https://github.com/evanmunro/design-of-simulations can not open

**Comment by evanmunro** [comment]
The updated link is http://github.com/gsbdbi/ds-wgan

**Comment by 1013hdh** [comment]
Thanks a lot
